services:
  postgres_db:
    image: postgres:15-alpine
    container_name: skills_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: course_recommendation_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d course_recommendation_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skills_app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres_db:5432/course_recommendation_db
      SECRET_KEY: change-this-later
      JWT_SECRET_KEY: change-this-later
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data:
